In [1]:
import numpy as np
import pandas as pd
from pandas.tseries.offsets import MonthEnd
import datetime
import calendar

## EDA and data cleaning

In [2]:
df = pd.read_csv('Q1_2020_Data_analyst_transactions.csv')

df.head()

,id,Date of Sale (dd/mm/yyyy),Address,Postal Code,County,Price,Not Full Market Price,VAT Exclusive,Description of Property,Property Size Description
0,1,01/01/2010,"5 Braemor Drive, Churchtown, Co.Dublin",NaN,Dublin,"343,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN
1,2,03/01/2010,"134 Ashewood Walk, Summerhill Lane, Portlaoise",NaN,Laois,"185,000.00",No,Yes,New Dwelling house /Apartment,greater than or equal to 38 sq metres and less...
2,11,04/01/2010,"16 Aisling Geal, Fr. Russell Road",NaN,Limerick,"110,000.00",No,No,New Dwelling house /Apartment,greater than or equal to 38 sq metres and less...
3,21,04/01/2010,"48 KILLIANS COURT, MULLAGH",NaN,Cavan,"122,000.00",No,Yes,New Dwelling house /Apartment,greater than 125 sq metres
4,35,04/01/2010,"Knock, Lanesboro",NaN,Longford,"125,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 410523 entries, 0 to 410522
Data columns (total 10 columns):
id                           410523 non-null int64
Date of Sale (dd/mm/yyyy)    410523 non-null object
Address                      410523 non-null object
Postal Code                  76876 non-null object
County                       410523 non-null object
Price                        410523 non-null object
Not Full Market Price        410523 non-null object
VAT Exclusive                410523 non-null object
Description of Property      410523 non-null object
Property Size Description    52567 non-null object
dtypes: int64(1), object(9)
memory usage: 31.3+ MB

We explore the data, we notice that Postal Code have a lot of missing values. This shouldn't surprise, as the PostCode in Ireland are pretty recent. Another variable with high degree of missing values is Property SIze Description.

# Report script

Here, we generate the script that ingest the raw data, manipulate the data and transform it to the expected output.

We notice that the date of Sale is in the object format. We want to transform it into a datetime so it would be easier to treat it later on. Also, I want to change the name column to have an easier handle and to match the final export sheet.

Since we are here, I want to rename the columns to the final layout: 
- id	
- Date	
- Address	
- Postal Code	
- County	
- Price	
- Not Full Market Price	
- VAT Exclusive	
- Description of Property	
- Property Size Description

In [4]:
# the only column to be renamed is the Date column

df.rename(columns = {'Date of Sale (dd/mm/yyyy)':'Date'}, inplace = True)
df['Date'] = pd.to_datetime(df['Date'])
df.head()

,id,Date,Address,Postal Code,County,Price,Not Full Market Price,VAT Exclusive,Description of Property,Property Size Description
0,1,2010-01-01,"5 Braemor Drive, Churchtown, Co.Dublin",NaN,Dublin,"343,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN
1,2,2010-03-01,"134 Ashewood Walk, Summerhill Lane, Portlaoise",NaN,Laois,"185,000.00",No,Yes,New Dwelling house /Apartment,greater than or equal to 38 sq metres and less...
2,11,2010-04-01,"16 Aisling Geal, Fr. Russell Road",NaN,Limerick,"110,000.00",No,No,New Dwelling house /Apartment,greater than or equal to 38 sq metres and less...
3,21,2010-04-01,"48 KILLIANS COURT, MULLAGH",NaN,Cavan,"122,000.00",No,Yes,New Dwelling house /Apartment,greater than 125 sq metres
4,35,2010-04-01,"Knock, Lanesboro",NaN,Longford,"125,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN

We want now to generate an additional label for the Province. A google search allow us to identify the counties that are associated with each province. The definitons are: 

Irish Provinces:
- Leinster (https://it.wikipedia.org/wiki/Leinster) => Carlow, Dublin, Kildare, Kilkenny, Laois, Longford, Louth, Meath, Offaly, Westmeath, Wexford e Wicklow.
- Ulster (https://it.wikipedia.org/wiki/Ulster) => Antrim, Armagh, Down, Fermanagh, Londonderry Tyrone, Cavan, Donegal, Monaghan
- Munster (https://it.wikipedia.org/wiki/Munster) => Cork, Clare, Kerry, Limerick, Tipperary, Waterford
- Connaught (https://it.wikipedia.org/wiki/Connaught) =>  Galway, Leitrim, Mayo, Roscommon, Sligo

In [36]:
prov_label = {['Carlow', 'Dublin', 'Kildare', 'Kilkenny', 'Laois', 
                           'Longford', 'Louth', 'Meath', 'Offaly', 'Westmeath', 'Wexford' 'Wicklow']:'Leinster', 
             'Ulster': ['Antrim', 'Armagh', 'Down', 'Fermanagh', 'Londonderry' 
                        'Tyrone', 'Cavan', 'Donegal', 'Monaghan'], 
             'Munster' : ['Cork', 'Clare', 'Kerry', 'Limerick', 'Tipperary', 'Waterford'],
             'Connaught': ['Galway', 'Leitrim', 'Mayo', 'Roscommon', 'Sligo']}


# Using list comprehension 
# Iterating through value lists dictionary 

df['Province'] = df['County'].map(prov_label)
df.head()

TypeError: unhashable type: 'list'

Here, we want to extract the last day of the month

In [6]:


df['Month_end_day'] = pd.to_datetime(df['Date'], format="%Y%m") + MonthEnd(0)

df.head()

,id,Date,Address,Postal Code,County,Price,Not Full Market Price,VAT Exclusive,Description of Property,Property Size Description,Province,Month_end_day
0,1,2010-01-01,"5 Braemor Drive, Churchtown, Co.Dublin",NaN,Dublin,"343,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN,Leinster,2010-01-31
1,2,2010-03-01,"134 Ashewood Walk, Summerhill Lane, Portlaoise",NaN,Laois,"185,000.00",No,Yes,New Dwelling house /Apartment,greater than or equal to 38 sq metres and less...,Leinster,2010-03-31
2,11,2010-04-01,"16 Aisling Geal, Fr. Russell Road",NaN,Limerick,"110,000.00",No,No,New Dwelling house /Apartment,greater than or equal to 38 sq metres and less...,Leinster,2010-04-30
3,21,2010-04-01,"48 KILLIANS COURT, MULLAGH",NaN,Cavan,"122,000.00",No,Yes,New Dwelling house /Apartment,greater than 125 sq metres,Leinster,2010-04-30
4,35,2010-04-01,"Knock, Lanesboro",NaN,Longford,"125,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN,Leinster,2010-04-30

Postal code is not a requirement for our output. However, we don't want to lose this information. We will fill the null values with a text label. We apply the same temporarily for Property Size and Description

In [7]:
df['Postal Code'] = df['Postal Code'].fillna('unavailable')
df['Property Size Description'] = df['Property Size Description'].fillna('unavailable')

df.head()

,id,Date,Address,Postal Code,County,Price,Not Full Market Price,VAT Exclusive,Description of Property,Property Size Description,Province,Month_end_day
0,1,2010-01-01,"5 Braemor Drive, Churchtown, Co.Dublin",unavailable,Dublin,"343,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-01-31
1,2,2010-03-01,"134 Ashewood Walk, Summerhill Lane, Portlaoise",unavailable,Laois,"185,000.00",No,Yes,New Dwelling house /Apartment,greater than or equal to 38 sq metres and less...,Leinster,2010-03-31
2,11,2010-04-01,"16 Aisling Geal, Fr. Russell Road",unavailable,Limerick,"110,000.00",No,No,New Dwelling house /Apartment,greater than or equal to 38 sq metres and less...,Leinster,2010-04-30
3,21,2010-04-01,"48 KILLIANS COURT, MULLAGH",unavailable,Cavan,"122,000.00",No,Yes,New Dwelling house /Apartment,greater than 125 sq metres,Leinster,2010-04-30
4,35,2010-04-01,"Knock, Lanesboro",unavailable,Longford,"125,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 410523 entries, 0 to 410522
Data columns (total 12 columns):
id                           410523 non-null int64
Date                         410523 non-null datetime64[ns]
Address                      410523 non-null object
Postal Code                  410523 non-null object
County                       410523 non-null object
Price                        410523 non-null object
Not Full Market Price        410523 non-null object
VAT Exclusive                410523 non-null object
Description of Property      410523 non-null object
Property Size Description    410523 non-null object
Province                     410523 non-null object
Month_end_day                410523 non-null datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(9)
memory usage: 37.6+ MB

To evaluate duplicate transactions, we can evaluate if there are multiple ids

In [9]:
df['id'].nunique()

410523

In [10]:
# explore address to evaluate if there are duplicates in these rows
print(df['Address'].str.lower().nunique())

# we transform all address values in lower string 
df['Address_lower'] = df['Address'].str.lower()

print(df['Address'].str.lower().nunique())

383312
383312

It seems that there are no duplicate ids, but there are duplicated addresses in the dataset. This could suggest the presence of duplicate transactions

since the transaction will associate likely the address and the price, we can check if we have duplicates when we concatenate the two information

In [11]:
# sorting by first name 
df.sort_values("Address_lower").head(30)

,id,Date,Address,Postal Code,County,Price,Not Full Market Price,VAT Exclusive,Description of Property,Property Size Description,Province,Month_end_day,Address_lower
297116,297168,2018-12-02,"!5 Ard Coillte, Ballina",unavailable,Tipperary,"281,939.00",No,Yes,New Dwelling house /Apartment,greater than or equal to 125 sq metres,Leinster,2018-12-31,"!5 ard coillte, ballina"
339572,339635,2018-11-15,"!9 Blossomhill, Broomfield Village, Midleton",unavailable,Cork,"321,585.00",No,Yes,New Dwelling house /Apartment,greater than or equal to 38 sq metres and less...,Leinster,2018-11-30,"!9 blossomhill, broomfield village, midleton"
395689,395858,2019-10-31,"!A Taylor Hill Crescent, Naul Road, Balbriggan",unavailable,Dublin,"273,128.75",No,Yes,New Dwelling house /Apartment,unavailable,Leinster,2019-10-31,"!a taylor hill crescent, naul road, balbriggan"
153287,153300,2015-05-05,"#392 The Oak, Trimbleston, Goatstown Road",Dublin 14,Dublin,"375,770.93",No,Yes,New Dwelling house /Apartment,greater than or equal to 38 sq metres and less...,Leinster,2015-05-31,"#392 the oak, trimbleston, goatstown road"
153288,153301,2015-05-05,"#396 The Oak, Trimbleston, Goatstown Road",Dublin 14,Dublin,"375,770.93",No,Yes,New Dwelling house /Apartment,greater than or equal to 38 sq metres and less...,Leinster,2015-05-31,"#396 the oak, trimbleston, goatstown road"
258701,258694,2017-06-19,#NAME?,unavailable,Carlow,"48,000.00",Yes,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2017-06-30,#name?
342264,342374,2018-11-29,"& James Fort Avenue, Kinsale",unavailable,Cork,"273,127.00",No,Yes,New Dwelling house /Apartment,unavailable,Leinster,2018-11-30,"& james fort avenue, kinsale"
20974,20970,2010-12-30,"' Adrigole', Ballincurrig, Douglas",unavailable,Cork,"360,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-12-31,"' adrigole', ballincurrig, douglas"
67579,67515,2013-02-25,"' Bedford', Killiney Ave, Killiney",unavailable,Dublin,"800,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2013-02-28,"' bedford', killiney ave, killiney"
14913,14892,2010-09-24,"' Fishermans Cottage', Bawnbrack, Golden",unavailable,Tipperary,"115,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-09-30,"' fishermans cottage', bawnbrack, golden"
54576,54558,2012-09-18,"' St. Martins', Ightermurragh, Ladysbridge",unavailable,Cork,"118,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2012-09-30,"' st. martins', ightermurragh, ladysbridge"
39899,39866,2012-01-16,"' The Stone House', Ballyglass Upper, Tipperary",unavailable,Tipperary,"210,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2012-01-31,"' the stone house', ballyglass upper, tipperary"
218430,218388,2016-08-09,"''ARD PATRICK'', CREADEN, NEAR DUNMORE EAST",unavailable,Waterford,"117,500.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2016-08-31,"''ard patrick'', creaden, near dunmore east"
189139,189064,2016-01-22,"''CRANHURST'', BALLYCAPPLE, CLOUGHJORDAN",unavailable,Tipperary,"145,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2016-01-31,"''cranhurst'', ballycapple, cloughjordan"
136736,136137,2014-12-22,"''FAHAN'', 1 PEARSE ROAD, SLIGO",unavailable,Sligo,"85,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2014-12-31,"''fahan'', 1 pearse road, sligo"
371524,371505,2019-11-06,"''FAIRVIEW'', 1A MEETING HOUSE LANE, LINENHALL...",unavailable,Louth,"108,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"''fairview'', 1a meeting house lane, linenhall..."
78306,78144,2013-07-26,"''HILLTOP'', OUGHILL, REDCROSS",unavailable,Wicklow,"265,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2013-07-31,"''hilltop'', oughill, redcross"
170816,170745,2015-09-14,"''LITTLE BAMBOO'', 1 BEARLOUGH, BLIND LANE",unavailable,Wexford,"200,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2015-09-30,"''little bamboo'', 1 bearlough, blind lane"
89088,88976,2013-11-22,"''LYNFIELD'', EMOCLEW ROAD, ARKLOW",unavailable,Wicklow,"150,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2013-11-30,"''lynfield'', emoclew road, arklow"
232274,232042,2016-07-12,"''THE BUNGALOW'', BALLYHARA, KILBRIDE",unavailable,Wicklow,"515,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2016-07-31,"''the bungalow'', ballyhara, kilbride"
201878,201774,2016-09-05,"''TIBURON'', BURKES HILL, LOTAMORE",unavailable,Cork,"395,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2016-09-30,"''tiburon'', burkes hill, lotamore"
357,328,2010-01-14,"''Villa Bosco'', Newtown, Co Waterfod",unavailable,Waterford,"258,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-01-31,"''villa bosco'', newtown, co waterfod"
61893,61745,2012-12-12,"'Abhann', 61 Dublin Road, Swords",unavailable,Dublin,"496,089.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2012-12-31,"'abhann', 61 dublin road, swords"
345763,345697,2018-12-14,"'ADAIR COTTAGE', TREMANE, CO ROSCOMMON",unavailable,Roscommon,"109,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2018-12-31,"'adair cottage', tremane, co roscommon"
85059,84992,2013-11-10,"'Airmount', Kingswell, Tipperary",unavailable,Tipperary,"141,847.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2013-11-30,"'airmount', kingswell, tipperary"
129448,129304,2014-11-20,"'Aisling', Bellinter, Navan",unavailable,Meath,"260,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2014-11-30,"'aisling', bellinter, navan"
287719,287687,2017-12-12,"'AISLING', CLANCY TERRACE, CHARLEVILLE",unavailable,Cork,"72,500.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2017-12-31,"'aisling', clancy terrace, charleville"
17317,17277,2010-02-11,"'Aisling', Piedmont, Jenkinstown",unavailable,Louth,"300,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-02-28,"'aisling', piedmont, jenkinstown"
38602,38482,2011-12-19,"'Alcove', Barnhill Road, Dalkey",unavailable,Dublin,"365,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2011-12-31,"'alcove', barnhill road, dalkey"
5944,5874,2010-04-05,"'Allendale', 66 Highfield Road, Rathgar",Dublin 6,Dublin,"2,150,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"'allendale', 66 highfield road, rathgar"

We also have some inconsistency in termsof how the address are reported. A further step would be to combine address and price of the house to match two different flags

In [12]:
# copy the data set first
df_o = df.copy()

In [13]:
df_o.drop_duplicates(subset ="Address_lower", 
                     keep = 'first', inplace = True) 

df_o['Address'].str.lower().nunique()

383312

We can evaluate how much information we lost based on the output we want to get. In particular, let's try to evaluate the information lost in the time frame we are interested in

In [14]:
mask = (df['Month_end_day'] > '2014-01-31') & (df['Month_end_day'] <= '2019-12-31')

df.loc[mask]['Address'].str.lower().nunique()

289758

In [15]:
mask = (df_o['Month_end_day'] > '2014-01-31') & (df_o['Month_end_day'] <= '2019-12-31')

df_o.loc[mask]['Address'].str.lower().nunique()

286081

we lost 287810 /289758 (ca 1%) of the information

In [16]:
df_o['Description of Property'].unique()

array(['Second-Hand Dwelling house /Apartment',
       'New Dwelling house /Apartment', 'Teach/¡ras·n CÛnaithe Ath·imhe',
       'Teach/¡ras·n CÛnaithe Nua', 'Teach/?ras?n C?naithe Nua'],
      dtype=object)

In [17]:
df_o.groupby('Description of Property')['id'].count()

Description of Property
New Dwelling house /Apartment             64595
Second-Hand Dwelling house /Apartment    318687
Teach/?ras?n C?naithe Nua                     1
Teach/¡ras·n CÛnaithe Ath·imhe               27
Teach/¡ras·n CÛnaithe Nua                     2
Name: id, dtype: int64

We have few property description that are quite strange. Not sure at the moment if we want to keep those or not. But consider.

In [18]:
df_o.loc[df_o['Description of Property'].str.contains("Teach") ]

,id,Date,Address,Postal Code,County,Price,Not Full Market Price,VAT Exclusive,Description of Property,Property Size Description,Province,Month_end_day,Address_lower
1160,1145,2010-01-02,"247 GLANNTAN, GOLF LINKS ROAD, CASTLETROY.",NÌ Bhaineann,Limerick,"228,500.00",No,No,Teach/¡ras·n CÛnaithe Ath·imhe,unavailable,Leinster,2010-01-31,"247 glanntan, golf links road, castletroy."
12764,12751,2010-08-20,"8 Millhill Park, Skerries.",unavailable,Dublin,"320,000.00",No,No,Teach/¡ras·n CÛnaithe Ath·imhe,unavailable,Leinster,2010-08-31,"8 millhill park, skerries."
17324,17312,2010-02-11,"Carrigvore, Killiskey.",unavailable,Wicklow,"610,000.00",No,No,Teach/¡ras·n CÛnaithe Ath·imhe,unavailable,Leinster,2010-02-28,"carrigvore, killiskey."
20034,20121,2010-12-16,"7 Cul Na Toinne, Bunbeg.",unavailable,Donegal,"74,889.87",No,Yes,Teach/¡ras·n CÛnaithe Nua,nÌos mÛ n· nÛ cothrom le 38 mÈadar cearnach ag...,Leinster,2010-12-31,"7 cul na toinne, bunbeg."
22624,22655,2011-02-16,"Racecourse Road, Roscommon.",NÌ Bhaineann,Roscommon,"100,000.00",No,No,Teach/¡ras·n CÛnaithe Ath·imhe,unavailable,Leinster,2011-02-28,"racecourse road, roscommon."
26873,26791,2011-05-27,"12 Southdene, Gleann Bhaile Na Manach, Baile N...",Baile ¡tha Cliath 14,Dublin,"272,000.00",No,No,Teach/¡ras·n CÛnaithe Ath·imhe,unavailable,Leinster,2011-05-31,"12 southdene, gleann bhaile na manach, baile n..."
32172,32198,2011-07-09,"Station road, Castlebellingham, Dundalk.",unavailable,Louth,"179,000.00",No,No,Teach/¡ras·n CÛnaithe Ath·imhe,unavailable,Leinster,2011-07-31,"station road, castlebellingham, dundalk."
39758,39774,2012-12-01,"Apartment 12 Block B, Corofin House Clare Vi...",Baile ?tha Cliath 17,Dublin,"115,045.00",No,Yes,Teach/?ras?n C?naithe Nua,n?os l? n? 38 m?adar cearnach,Leinster,2012-12-31,"apartment 12 block b, corofin house clare vi..."
48868,48861,2012-06-28,"7 Thorndale Grove, Artane, Dublin.",Baile ¡tha Cliath 5,Dublin,"250,000.00",No,No,Teach/¡ras·n CÛnaithe Ath·imhe,unavailable,Leinster,2012-06-30,"7 thorndale grove, artane, dublin."
54057,53982,2012-10-09,"121 Ardilaun, Portmarnock, Co Dublin.",NÌ Bhaineann,Dublin,"375,000.00",No,No,Teach/¡ras·n CÛnaithe Ath·imhe,unavailable,Leinster,2012-10-31,"121 ardilaun, portmarnock, co dublin."
59728,59616,2012-11-22,"104 Shandon Park, Phibsborough, Dublin 7",unavailable,Dublin,"290,000.00",No,No,Teach/¡ras·n CÛnaithe Ath·imhe,unavailable,Leinster,2012-11-30,"104 shandon park, phibsborough, dublin 7"
61722,61695,2012-11-12,"58 Bunbury Gate Crescent, Swords, Co. Dublin",unavailable,Dublin,"325,000.00",No,No,Teach/¡ras·n CÛnaithe Ath·imhe,unavailable,Leinster,2012-11-30,"58 bunbury gate crescent, swords, co. dublin"
62355,62112,2012-12-14,"187 Vernon Avenue, Clontarf",Baile ¡tha Cliath 3,Dublin,"440,000.00",No,No,Teach/¡ras·n CÛnaithe Ath·imhe,unavailable,Leinster,2012-12-31,"187 vernon avenue, clontarf"
71798,71715,2013-03-05,"23 Riversdale Court, Monkstown",unavailable,Dublin,"315,000.00",No,No,Teach/¡ras·n CÛnaithe Ath·imhe,unavailable,Leinster,2013-03-31,"23 riversdale court, monkstown"
77253,77238,2013-07-16,"87 BÛthar an Bhreatnaigh, Droim Conrach, B.¡.C 3",Baile ¡tha Cliath 3,Dublin,"198,000.00",No,No,Teach/¡ras·n CÛnaithe Ath·imhe,unavailable,Leinster,2013-07-31,"87 bûthar an bhreatnaigh, droim conrach, b.¡.c 3"
92212,92294,2013-12-17,"DURHAMSTOWN, BOHERMEEN, NAVAN",unavailable,Meath,"160,000.00",No,No,Teach/¡ras·n CÛnaithe Ath·imhe,unavailable,Leinster,2013-12-31,"durhamstown, bohermeen, navan"
112419,112411,2014-07-14,"57 GRANGE LODGE AVE, BEAUPARK, DONAGHMEDE",Baile ¡tha Cliath 15,Dublin,"250,000.00",No,No,Teach/¡ras·n CÛnaithe Ath·imhe,unavailable,Leinster,2014-07-31,"57 grange lodge ave, beaupark, donaghmede"
122988,122713,2014-03-10,"16 BLOOMFIELD PARK, BLOOMFIELD AVE, DONNYBROOK...",Baile ¡tha Cliath 4,Dublin,"531,867.00",No,No,Teach/¡ras·n CÛnaithe Ath·imhe,unavailable,Leinster,2014-03-31,"16 bloomfield park, bloomfield ave, donnybrook..."
127059,126802,2014-10-31,"13 Seachnall Abbey, Dunshaughlin",unavailable,Meath,"369,600.00",No,Yes,Teach/¡ras·n CÛnaithe Nua,nÌos mÛ n· nÛ cothrom le 38 mÈadar cearnach ag...,Leinster,2014-10-31,"13 seachnall abbey, dunshaughlin"
167011,166984,2015-08-17,"27 O'CONNELL CRESCENT, CORK",unavailable,Cork,"175,000.00",No,No,Teach/¡ras·n CÛnaithe Ath·imhe,unavailable,Leinster,2015-08-31,"27 o'connell crescent, cork"
169941,169946,2015-07-09,"Cruagh Cottage, Slieveroe, Riverstick Cork.",NÌ Bhaineann,Cork,"390,000.00",No,No,Teach/¡ras·n CÛnaithe Ath·imhe,unavailable,Leinster,2015-07-31,"cruagh cottage, slieveroe, riverstick cork."
190638,190545,2016-04-02,"109 ALEXANDRA WALK, CLANE, KILDARE",unavailable,Kildare,"267,000.00",No,No,Teach/¡ras·n CÛnaithe Ath·imhe,unavailable,Leinster,2016-04-30,"109 alexandra walk, clane, kildare"
206357,206259,2016-06-13,"10 BELTON PARK RD, DONNYCARNEY, DUBLIN 9",Baile ¡tha Cliath 9,Dublin,"342,000.00",No,No,Teach/¡ras·n CÛnaithe Ath·imhe,unavailable,Leinster,2016-06-30,"10 belton park rd, donnycarney, dublin 9"
216409,216507,2016-08-25,"DROMQUIN, BAREFIELD, ENNIS",unavailable,Clare,"160,000.00",Yes,No,Teach/¡ras·n CÛnaithe Ath·imhe,unavailable,Leinster,2016-08-31,"dromquin, barefield, ennis"
238357,238416,2017-01-16,"62 PEBBLE BEACH, TRAMORE, WATERFORD",unavailable,Waterford,"65,000.00",No,No,Teach/¡ras·n CÛnaithe Ath·imhe,unavailable,Leinster,2017-01-31,"62 pebble beach, tramore, waterford"
281903,281819,2017-09-11,"60 SANDYFORD DOWNS, SANDYFORD, DUBLIN 18",Baile ¡tha Cliath 18,Dublin,"580,000.00",No,No,Teach/¡ras·n CÛnaithe Ath·imhe,unavailable,Leinster,2017-09-30,"60 sandyford downs, sandyford, dublin 18"
321081,320973,2018-07-25,"18 MOUNT PLEASANT DR, MOUNT PLEASANT, WATERFORD",unavailable,Waterford,"281,500.00",No,No,Teach/¡ras·n CÛnaithe Ath·imhe,unavailable,Leinster,2018-07-31,"18 mount pleasant dr, mount pleasant, waterford"
324222,324091,2018-08-15,"15 WOODSIDE HALL, TICKNOCK, SANDYFORD DUBLIN 18",Baile ¡tha Cliath 18,Dublin,"300,000.00",Yes,No,Teach/¡ras·n CÛnaithe Ath·imhe,unavailable,Leinster,2018-08-31,"15 woodside hall, ticknock, sandyford dublin 18"
363613,363602,2019-04-15,"GARRYOWEN, BALLINAHINCH, NEWTOWNMOUNTKENNEDY",unavailable,Wicklow,"530,000.00",No,No,Teach/¡ras·n CÛnaithe Ath·imhe,unavailable,Leinster,2019-04-30,"garryowen, ballinahinch, newtownmountkennedy"
364731,364859,2019-04-25,"MAIN ST, DUNFANAGHY, LETTERKENNY",unavailable,Donegal,"117,500.00",No,No,Teach/¡ras·n CÛnaithe Ath·imhe,unavailable,Leinster,2019-04-30,"main st, dunfanaghy, letterkenny"

It looks like they are all related with Leinster, so dropping them won't hurt the final output

We want to evaluate the purchase in bulk. A naive approach could be to identify the purchases that happened in the same date for the same property.

In [31]:
pd.concat([df_o, df_o['Address_lower'].str.split(', ', expand=True)], axis=1)

,id,Date,Address,Postal Code,County,Price,Not Full Market Price,VAT Exclusive,Description of Property,Property Size Description,Province,Month_end_day,Address_lower,0,1,2,0,1,2
0,1,2010-01-01,"5 Braemor Drive, Churchtown, Co.Dublin",unavailable,Dublin,"343,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-01-31,"5 braemor drive, churchtown, co.dublin",5 braemor drive,churchtown,co.dublin,5 braemor drive,churchtown,co.dublin
1,2,2010-03-01,"134 Ashewood Walk, Summerhill Lane, Portlaoise",unavailable,Laois,"185,000.00",No,Yes,New Dwelling house /Apartment,greater than or equal to 38 sq metres and less...,Leinster,2010-03-31,"134 ashewood walk, summerhill lane, portlaoise",134 ashewood walk,summerhill lane,portlaoise,134 ashewood walk,summerhill lane,portlaoise
2,11,2010-04-01,"16 Aisling Geal, Fr. Russell Road",unavailable,Limerick,"110,000.00",No,No,New Dwelling house /Apartment,greater than or equal to 38 sq metres and less...,Leinster,2010-04-30,"16 aisling geal, fr. russell road",16 aisling geal,fr. russell road,None,16 aisling geal,fr. russell road,None
3,21,2010-04-01,"48 KILLIANS COURT, MULLAGH",unavailable,Cavan,"122,000.00",No,Yes,New Dwelling house /Apartment,greater than 125 sq metres,Leinster,2010-04-30,"48 killians court, mullagh",48 killians court,mullagh,None,48 killians court,mullagh,None
4,35,2010-04-01,"Knock, Lanesboro",unavailable,Longford,"125,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"knock, lanesboro",knock,lanesboro,None,knock,lanesboro,None
5,10,2010-04-01,"15a Moore Bay, Kilkee",unavailable,Clare,"126,500.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"15a moore bay, kilkee",15a moore bay,kilkee,None,15a moore bay,kilkee,None
6,25,2010-04-01,"59 ormond keep, nenagh",unavailable,Tipperary,"128,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"59 ormond keep, nenagh",59 ormond keep,nenagh,None,59 ormond keep,nenagh,None
7,26,2010-04-01,"66 Rory O'Connor Place, Arklow",unavailable,Wicklow,"145,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"66 rory o'connor place, arklow",66 rory o'connor place,arklow,None,66 rory o'connor place,arklow,None
8,32,2010-04-01,"Cloonlaughnan, Mount Talbot",unavailable,Roscommon,"145,000.00",No,Yes,New Dwelling house /Apartment,greater than 125 sq metres,Leinster,2010-04-30,"cloonlaughnan, mount talbot",cloonlaughnan,mount talbot,None,cloonlaughnan,mount talbot,None
9,28,2010-04-01,"90 Suncroft Drive, Tallaght, Dublin 24",unavailable,Dublin,"147,950.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"90 suncroft drive, tallaght, dublin 24",90 suncroft drive,tallaght,dublin 24,90 suncroft drive,tallaght,dublin 24
10,5,2010-04-01,"11 Melville Heights, Kilkenny",unavailable,Kilkenny,"160,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"11 melville heights, kilkenny",11 melville heights,kilkenny,None,11 melville heights,kilkenny,None
11,42,2010-04-01,"The Greenway, Mofel Farm Road, Cork",unavailable,Cork,"160,000.00",Yes,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"the greenway, mofel farm road, cork",the greenway,mofel farm road,cork,the greenway,mofel farm road,cork
12,37,2010-04-01,"No. 11, Charlotte Quay",unavailable,Limerick,"164,167.00",No,Yes,New Dwelling house /Apartment,greater than or equal to 38 sq metres and less...,Leinster,2010-04-30,"no. 11, charlotte quay",no. 11,charlotte quay,None,no. 11,charlotte quay,None
13,38,2010-04-01,"No. 12, Charlotte Quay",unavailable,Limerick,"164,167.00",No,Yes,New Dwelling house /Apartment,greater than or equal to 38 sq metres and less...,Leinster,2010-04-30,"no. 12, charlotte quay",no. 12,charlotte quay,None,no. 12,charlotte quay,None
14,39,2010-04-01,"No. 13, Charlotte Quay",unavailable,Limerick,"164,167.00",No,Yes,New Dwelling house /Apartment,greater than or equal to 38 sq metres and less...,Leinster,2010-04-30,"no. 13, charlotte quay",no. 13,charlotte quay,None,no. 13,charlotte quay,None
15,40,2010-04-01,"No. 18, Charlotte Quay",unavailable,Limerick,"164,167.00",No,Yes,New Dwelling house /Apartment,greater than or equal to 38 sq metres and less...,Leinster,2010-04-30,"no. 18, charlotte quay",no. 18,charlotte quay,None,no. 18,charlotte quay,None
16,7,2010-04-01,"13 Oakleigh Wood, Dooradoyle, Limerick",unavailable,Limerick,"172,500.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"13 oakleigh wood, dooradoyle, limerick",13 oakleigh wood,dooradoyle,limerick,13 oakleigh wood,dooradoyle,limerick
17,36,2010-04-01,"No. 11 Blackrock Court, Quay Road, Ballina",unavailable,Mayo,"172,500.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"no. 11 blackrock court, quay road, ballina",no. 11 blackrock court,quay road,ballina,no. 11 blackrock court,quay road,ballina
18,8,2010-04-01,"13 The Drive, Chapelstown Gate, Tullow Road",unavailable,Carlow,"177,500.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"13 the drive, chapelstown gate, tullow road",13 the drive,chapelstown gate,tullow road,13 the drive,chapelstown gate,tullow road
19,9,2010-04-01,"15 Carriglawn, Waterpark, Carrigaline",unavailable,Cork,"180,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"15 carriglawn, waterpark, carrigaline",15 carriglawn,waterpark,carrigaline,15 carriglawn,waterpark,carrigaline
20,23,2010-04-01,"5 Clancy Road, Finglas, Dublin 11",unavailable,Dublin,"205,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"5 clancy road, finglas, dublin 11",5 clancy road,finglas,dublin 11,5 clancy road,finglas,dublin 11
21,33,2010-04-01,"Killult, Falcarragh",unavailable,Donegal,"215,000.00",No,Yes,New Dwelling house /Apartment,greater than 125 sq metres,Leinster,2010-04-30,"killult, falcarragh",killult,falcarragh,None,killult,falcarragh,None
22,29,2010-04-01,"Aughmagree, Kilteevan",unavailable,Roscommon,"215,000.00",No,Yes,New Dwelling house /Apartment,greater than 125 sq metres,Leinster,2010-04-30,"aughmagree, kilteevan",aughmagree,kilteevan,None,aughmagree,kilteevan,None
23,19,2010-04-01,"4 Hawthorn Court, Collooney",unavailable,Sligo,"220,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"4 hawthorn court, collooney",4 hawthorn court,collooney,None,4 hawthorn court,collooney,None
24,31,2010-04-01,"CARROWTRASNA, CARROWMORE LACKEN, BALLINA",unavailable,Mayo,"245,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"carrowtrasna, carrowmore lacken, ballina",carrowtrasna,carrowmore lacken,ballina,carrowtrasna,carrowmore lacken,ballina
25,30,2010-04-01,"Ballyeden, Ballyoughter, Gorey",unavailable,Wexford,"255,022.00",No,Yes,New Dwelling house /Apartment,greater than 125 sq metres,Leinster,2010-04-30,"ballyeden, ballyoughter, gorey",ballyeden,ballyoughter,gorey,ballyeden,ballyoughter,gorey
26,16,2010-04-01,"25 Fairway Lawns, Bettystown",unavailable,Meath,"273,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"25 fairway lawns, bettystown",25 fairway lawns,bettystown,None,25 fairway lawns,bettystown,None
27,24,2010-04-01,"54., brides glen avenue, swords",unavailable,Dublin,"337,500.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"54., brides glen avenue, swords",54.,brides glen avenue,swords,54.,brides glen avenue,swords
28,43,2010-04-01,"The Mews, 11A Wyckham Park Road, Dundrum",Dublin 14,Dublin,"345,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"the mews, 11a wyckham park road, dundrum",the mews,11a wyckham park road,dundrum,the mews,11a wyckham park road,dundrum
29,20,2010-04-01,"44 Allen Park Road, Stillorgan, County Dublin",unavailable,Dublin,"350,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"44 allen park road, stillorgan, county dublin",44 allen park road,stillorgan,county dublin,44 allen park road,stillorgan,county dublin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
410493,896601,2019-06-11,"4 CARA STREET, CLONES, CO MONAGHAN",unavailable,Monaghan,"40,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-06-30,"4 cara street, clones, co monaghan",4 cara street,clones,co monaghan,4 cara street,clones,co monaghan
410494,896615,2019-06-11,"5 CARA ST, CLONES, CO MONAGHAN",unavailable,Monaghan,"40,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-06-30,"5 cara st, clones, co monaghan",5 cara st,clones,co monaghan,5 cara st,clones,co monaghan
410495,896676,2019-06-11,"KILNACRANFY, CASTLEBLAYNEY, COUNTY MONAGHAN",unavailable,Monaghan,"100,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-06-30,"kilnacranfy, castleblayney, county monaghan",kilnacranfy,castleblayney,county monaghan,kilnacranfy,castleblayney,county monaghan
410496,896696,2019-06-11,"TULLYLISH, MONAGHAN",unavailable,Monaghan,"219,500.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-06-30,"tullylish, monaghan",tullylish,monaghan,None,tullylish,monaghan,None
410497,896873,2019-07-11,"CORRINENTY, CASTLEBLAYNEY, CO. MONAGHAN",unavailable,Monaghan,"26,250.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-07-31,"corrinenty, castleblayney, co. monaghan",corrinenty,castleblayney,co. monaghan,corrinenty,castleblayney,co. monaghan
410498,896828,2019-07-11,"7 THOMAS ST, CASTLEBLAYNEY, MONAGHAN",unavailable,Monaghan,"44,288.50",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-07-31,"7 thomas st, castleblayney, monaghan",7 thomas st,castleblayney,monaghan,7 thomas st,castleblayney,monaghan
410499,896797,2019-07-11,"43 TULLY, MONAGHAN, MONAGHAN",unavailable,Monaghan,"126,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-07-31,"43 tully, monaghan, monaghan",43 tully,monaghan,monaghan,43 tully,monaghan,monaghan
410500,896942,2019-08-11,"116 ONEILL PARK, CLONES, MONAGHAN",unavailable,Monaghan,"99,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-08-31,"116 oneill park, clones, monaghan",116 oneill park,clones,monaghan,116 oneill park,clones,monaghan
410501,897292,2019-11-11,"23/24 FERMANAGH ST, CLONES, CO MONAGHAN",unavailable,Monaghan,"20,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"23/24 fermanagh st, clones, co monaghan",23/24 fermanagh st,clones,co monaghan,23/24 fermanagh st,clones,co monaghan
410502,897779,2019-11-13,"NEWTOWNBUTLER RD, CLONES, MONAGHAN",unavailable,Monaghan,"50,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"newtownbutler rd, clones, monaghan",newtownbutler rd,clones,monaghan,newtownbutler rd,clones,monaghan
410503,897789,2019-11-13,"THE OLD SCHOOLHOUSE, CREEVE LATTON, CASTLEBLAY...",unavailable,Monaghan,"125,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"the old schoolhouse, creeve latton, castleblay...",the old schoolhouse,creeve latton,castleblayney p o,the old schoolhouse,creeve latton,castleblayney p o
410504,897766,2019-11-13,"DRUMLARA, TYDAVNET, MONAGHAN",unavailable,Monaghan,"200,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"drumlara, tydavnet, monaghan",drumlara,tydavnet,monaghan,drumlara,tydavnet,monaghan
410505,897840,2019-11-14,"162 MULLAGHMATT, MONAGHAN, CO. MONAGHAN",unavailable,Monaghan,"31,200.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"162 mullaghmatt, monaghan, co. monaghan",162 mullaghmatt,monaghan,co. monaghan,162 mullaghmatt,monaghan,co. monaghan
410506,897822,2019-11-14,"12 WOODLANDS, CARRICKMACROSS, CO. MONAGHAN",unavailable,Monaghan,"220,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"12 woodlands, carrickmacross, co. monaghan",12 woodlands,carrickmacross,co. monaghan,12 woodlands,carrickmacross,co. monaghan
410507,898186,2019-11-15,"2 COMMON COURT, THOMAS ST, CASTLEBLAYNEY",unavailable,Monaghan,"85,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"2 common court, thomas st, castleblayney",2 common court,thomas st,castleblayney,2 common court,thomas st,castleblayney
410508,898380,2019-11-15,"BEECHMOUNT, RAFEENAN, BALLINODE",unavailable,Monaghan,"212,500.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"beechmount, rafeenan, ballinode",beechmount,rafeenan,ballinode,beechmount,rafeenan,ballinode
410509,898393,2019-11-15,"CORRACLOUGHAN, CASTLEBLAYNEY, MONAGHAN",unavailable,Monaghan,"215,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"corracloughan, castleblayney, monaghan",corracloughan,castleblayney,monaghan,corracloughan,castleblayney,monaghan
410510,898521,2019-11-18,"39 CABRA, THREEMILEHOUSE, MONAGHAN",unavailable,Monaghan,"125,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"39 cabra, threemilehouse, monaghan",39 cabra,threemilehouse,monaghan,39 cabra,threemilehouse,monaghan
410511,898458,2019-11-18,"12 OAK RIDGE, MONAGHAN, MONAGHAN",unavailable,Monaghan,"195,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"12 oak ridge, monaghan, monaghan",12 oak ridge,monaghan,monaghan,12 oak ridge,monaghan,monaghan
410512,898520,2019-11-18,"38 MONTFORT, MONAGHAN, MONAGHAN",unavailable,Monaghan,"240,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"38 montfort, monaghan, monaghan",38 montfort,monaghan,monaghan,38 montfort,monaghan,monaghan
410513,898727,2019-11-19,"76 O'NEILL PARK, CLONES, COUNTY MONAGHAN",unavailable,Monaghan,"56,500.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"76 o'neill park, clones, county monaghan",76 o'neill park,clones,county monaghan,76 o'neill park,clones,county monaghan
410514,898658,2019-11-19,"188 BEECHGROVE LAWNS, DRUMBEAR, MONAGHAN TOWN",unavailable,Monaghan,"136,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"188 beechgrove lawns, drumbear, monaghan town",188 beechgrove lawns,drumbear,monaghan town,188 beechgrove lawns,drumbear,monaghan town
410515,898834,2019-11-20,"15 LATLORCAN GLEN, MONAGHAN, MONAGHAN",unavailable,Monaghan,"180,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"15 latlorcan glen, monaghan, monaghan",15 latlorcan glen,monaghan,monaghan,15 latlorcan glen,monaghan,monaghan
410516,899215,2019-11-21,"ARDKIRK, EMYVALE, MONAGHAN",unavailable,Monaghan,"155,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"ardkirk, emyvale, monaghan",ardkirk,emyvale,monaghan,ardkirk,emyvale,monaghan
410517,899158,2019-11-21,"53 ARDROSS AVE, CARRICKMACROSS, MONAGHAN",unavailable,Monaghan,"271,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"53 ardross ave, carrickmacross, monaghan",53 ardross ave,carrickmacross,monaghan,53 ardross ave,carrickmacross,monaghan
410518,899475,2019-11-22,"88 O'NEILL PARK, CLONES, CO MONAGHAN",unavailable,Monaghan,"35,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"88 o'neill park, clones, co monaghan",88 o'neill park,clones,co monaghan,88 o'neill park,clones,co monaghan
410519,899831,2019-11-26,"26 MULLACH GLAS CRESCENT, MONAGHAN, CO. MONAGH...",unavailable,Monaghan,"145,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"26 mullach glas crescent, monaghan, co. monagh...",26 mullach glas crescent,monaghan,co. monaghan,26 mullach glas crescent,monaghan,co. monaghan
410520,900375,2019-11-28,"6 MAPLE GROVE, SMITHBOROUGH, MONAGHAN",unavailable,Monaghan,"123,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"6 maple grove, smithborough, monaghan",6 maple grove,smithborough,monaghan,6 maple grove,smithborough,monaghan
410521,900345,2019-11-28,"4 BRAMLEY GROVE, CASTLEBLANEY, MONAGHAN",unavailable,Monaghan,"143,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"4 bramley grove, castleblaney, monaghan",4 bramley grove,castleblaney,monaghan,4 bramley grove,castleblaney,monaghan
410522,900559,2019-11-29,"14 ALDERWOOD, CLOUGHVALLEY, CARRICKMACROSS",unavailable,Monaghan,"195,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"14 alderwood, cloughvalley, carrickmacross",14 alderwood,cloughvalley,carrickmacross,14 alderwood,cloughvalley,carrickmacross

In [32]:
df_o

,id,Date,Address,Postal Code,County,Price,Not Full Market Price,VAT Exclusive,Description of Property,Property Size Description,Province,Month_end_day,Address_lower,0,1,2
0,1,2010-01-01,"5 Braemor Drive, Churchtown, Co.Dublin",unavailable,Dublin,"343,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-01-31,"5 braemor drive, churchtown, co.dublin",5 braemor drive,churchtown,co.dublin
1,2,2010-03-01,"134 Ashewood Walk, Summerhill Lane, Portlaoise",unavailable,Laois,"185,000.00",No,Yes,New Dwelling house /Apartment,greater than or equal to 38 sq metres and less...,Leinster,2010-03-31,"134 ashewood walk, summerhill lane, portlaoise",134 ashewood walk,summerhill lane,portlaoise
2,11,2010-04-01,"16 Aisling Geal, Fr. Russell Road",unavailable,Limerick,"110,000.00",No,No,New Dwelling house /Apartment,greater than or equal to 38 sq metres and less...,Leinster,2010-04-30,"16 aisling geal, fr. russell road",16 aisling geal,fr. russell road,None
3,21,2010-04-01,"48 KILLIANS COURT, MULLAGH",unavailable,Cavan,"122,000.00",No,Yes,New Dwelling house /Apartment,greater than 125 sq metres,Leinster,2010-04-30,"48 killians court, mullagh",48 killians court,mullagh,None
4,35,2010-04-01,"Knock, Lanesboro",unavailable,Longford,"125,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"knock, lanesboro",knock,lanesboro,None
5,10,2010-04-01,"15a Moore Bay, Kilkee",unavailable,Clare,"126,500.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"15a moore bay, kilkee",15a moore bay,kilkee,None
6,25,2010-04-01,"59 ormond keep, nenagh",unavailable,Tipperary,"128,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"59 ormond keep, nenagh",59 ormond keep,nenagh,None
7,26,2010-04-01,"66 Rory O'Connor Place, Arklow",unavailable,Wicklow,"145,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"66 rory o'connor place, arklow",66 rory o'connor place,arklow,None
8,32,2010-04-01,"Cloonlaughnan, Mount Talbot",unavailable,Roscommon,"145,000.00",No,Yes,New Dwelling house /Apartment,greater than 125 sq metres,Leinster,2010-04-30,"cloonlaughnan, mount talbot",cloonlaughnan,mount talbot,None
9,28,2010-04-01,"90 Suncroft Drive, Tallaght, Dublin 24",unavailable,Dublin,"147,950.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"90 suncroft drive, tallaght, dublin 24",90 suncroft drive,tallaght,dublin 24
10,5,2010-04-01,"11 Melville Heights, Kilkenny",unavailable,Kilkenny,"160,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"11 melville heights, kilkenny",11 melville heights,kilkenny,None
11,42,2010-04-01,"The Greenway, Mofel Farm Road, Cork",unavailable,Cork,"160,000.00",Yes,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"the greenway, mofel farm road, cork",the greenway,mofel farm road,cork
12,37,2010-04-01,"No. 11, Charlotte Quay",unavailable,Limerick,"164,167.00",No,Yes,New Dwelling house /Apartment,greater than or equal to 38 sq metres and less...,Leinster,2010-04-30,"no. 11, charlotte quay",no. 11,charlotte quay,None
13,38,2010-04-01,"No. 12, Charlotte Quay",unavailable,Limerick,"164,167.00",No,Yes,New Dwelling house /Apartment,greater than or equal to 38 sq metres and less...,Leinster,2010-04-30,"no. 12, charlotte quay",no. 12,charlotte quay,None
14,39,2010-04-01,"No. 13, Charlotte Quay",unavailable,Limerick,"164,167.00",No,Yes,New Dwelling house /Apartment,greater than or equal to 38 sq metres and less...,Leinster,2010-04-30,"no. 13, charlotte quay",no. 13,charlotte quay,None
15,40,2010-04-01,"No. 18, Charlotte Quay",unavailable,Limerick,"164,167.00",No,Yes,New Dwelling house /Apartment,greater than or equal to 38 sq metres and less...,Leinster,2010-04-30,"no. 18, charlotte quay",no. 18,charlotte quay,None
16,7,2010-04-01,"13 Oakleigh Wood, Dooradoyle, Limerick",unavailable,Limerick,"172,500.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"13 oakleigh wood, dooradoyle, limerick",13 oakleigh wood,dooradoyle,limerick
17,36,2010-04-01,"No. 11 Blackrock Court, Quay Road, Ballina",unavailable,Mayo,"172,500.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"no. 11 blackrock court, quay road, ballina",no. 11 blackrock court,quay road,ballina
18,8,2010-04-01,"13 The Drive, Chapelstown Gate, Tullow Road",unavailable,Carlow,"177,500.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"13 the drive, chapelstown gate, tullow road",13 the drive,chapelstown gate,tullow road
19,9,2010-04-01,"15 Carriglawn, Waterpark, Carrigaline",unavailable,Cork,"180,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"15 carriglawn, waterpark, carrigaline",15 carriglawn,waterpark,carrigaline
20,23,2010-04-01,"5 Clancy Road, Finglas, Dublin 11",unavailable,Dublin,"205,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"5 clancy road, finglas, dublin 11",5 clancy road,finglas,dublin 11
21,33,2010-04-01,"Killult, Falcarragh",unavailable,Donegal,"215,000.00",No,Yes,New Dwelling house /Apartment,greater than 125 sq metres,Leinster,2010-04-30,"killult, falcarragh",killult,falcarragh,None
22,29,2010-04-01,"Aughmagree, Kilteevan",unavailable,Roscommon,"215,000.00",No,Yes,New Dwelling house /Apartment,greater than 125 sq metres,Leinster,2010-04-30,"aughmagree, kilteevan",aughmagree,kilteevan,None
23,19,2010-04-01,"4 Hawthorn Court, Collooney",unavailable,Sligo,"220,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"4 hawthorn court, collooney",4 hawthorn court,collooney,None
24,31,2010-04-01,"CARROWTRASNA, CARROWMORE LACKEN, BALLINA",unavailable,Mayo,"245,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"carrowtrasna, carrowmore lacken, ballina",carrowtrasna,carrowmore lacken,ballina
25,30,2010-04-01,"Ballyeden, Ballyoughter, Gorey",unavailable,Wexford,"255,022.00",No,Yes,New Dwelling house /Apartment,greater than 125 sq metres,Leinster,2010-04-30,"ballyeden, ballyoughter, gorey",ballyeden,ballyoughter,gorey
26,16,2010-04-01,"25 Fairway Lawns, Bettystown",unavailable,Meath,"273,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"25 fairway lawns, bettystown",25 fairway lawns,bettystown,None
27,24,2010-04-01,"54., brides glen avenue, swords",unavailable,Dublin,"337,500.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"54., brides glen avenue, swords",54.,brides glen avenue,swords
28,43,2010-04-01,"The Mews, 11A Wyckham Park Road, Dundrum",Dublin 14,Dublin,"345,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"the mews, 11a wyckham park road, dundrum",the mews,11a wyckham park road,dundrum
29,20,2010-04-01,"44 Allen Park Road, Stillorgan, County Dublin",unavailable,Dublin,"350,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2010-04-30,"44 allen park road, stillorgan, county dublin",44 allen park road,stillorgan,county dublin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
410493,896601,2019-06-11,"4 CARA STREET, CLONES, CO MONAGHAN",unavailable,Monaghan,"40,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-06-30,"4 cara street, clones, co monaghan",4 cara street,clones,co monaghan
410494,896615,2019-06-11,"5 CARA ST, CLONES, CO MONAGHAN",unavailable,Monaghan,"40,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-06-30,"5 cara st, clones, co monaghan",5 cara st,clones,co monaghan
410495,896676,2019-06-11,"KILNACRANFY, CASTLEBLAYNEY, COUNTY MONAGHAN",unavailable,Monaghan,"100,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-06-30,"kilnacranfy, castleblayney, county monaghan",kilnacranfy,castleblayney,county monaghan
410496,896696,2019-06-11,"TULLYLISH, MONAGHAN",unavailable,Monaghan,"219,500.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-06-30,"tullylish, monaghan",tullylish,monaghan,None
410497,896873,2019-07-11,"CORRINENTY, CASTLEBLAYNEY, CO. MONAGHAN",unavailable,Monaghan,"26,250.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-07-31,"corrinenty, castleblayney, co. monaghan",corrinenty,castleblayney,co. monaghan
410498,896828,2019-07-11,"7 THOMAS ST, CASTLEBLAYNEY, MONAGHAN",unavailable,Monaghan,"44,288.50",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-07-31,"7 thomas st, castleblayney, monaghan",7 thomas st,castleblayney,monaghan
410499,896797,2019-07-11,"43 TULLY, MONAGHAN, MONAGHAN",unavailable,Monaghan,"126,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-07-31,"43 tully, monaghan, monaghan",43 tully,monaghan,monaghan
410500,896942,2019-08-11,"116 ONEILL PARK, CLONES, MONAGHAN",unavailable,Monaghan,"99,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-08-31,"116 oneill park, clones, monaghan",116 oneill park,clones,monaghan
410501,897292,2019-11-11,"23/24 FERMANAGH ST, CLONES, CO MONAGHAN",unavailable,Monaghan,"20,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"23/24 fermanagh st, clones, co monaghan",23/24 fermanagh st,clones,co monaghan
410502,897779,2019-11-13,"NEWTOWNBUTLER RD, CLONES, MONAGHAN",unavailable,Monaghan,"50,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"newtownbutler rd, clones, monaghan",newtownbutler rd,clones,monaghan
410503,897789,2019-11-13,"THE OLD SCHOOLHOUSE, CREEVE LATTON, CASTLEBLAY...",unavailable,Monaghan,"125,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"the old schoolhouse, creeve latton, castleblay...",the old schoolhouse,creeve latton,castleblayney p o
410504,897766,2019-11-13,"DRUMLARA, TYDAVNET, MONAGHAN",unavailable,Monaghan,"200,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"drumlara, tydavnet, monaghan",drumlara,tydavnet,monaghan
410505,897840,2019-11-14,"162 MULLAGHMATT, MONAGHAN, CO. MONAGHAN",unavailable,Monaghan,"31,200.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"162 mullaghmatt, monaghan, co. monaghan",162 mullaghmatt,monaghan,co. monaghan
410506,897822,2019-11-14,"12 WOODLANDS, CARRICKMACROSS, CO. MONAGHAN",unavailable,Monaghan,"220,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"12 woodlands, carrickmacross, co. monaghan",12 woodlands,carrickmacross,co. monaghan
410507,898186,2019-11-15,"2 COMMON COURT, THOMAS ST, CASTLEBLAYNEY",unavailable,Monaghan,"85,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"2 common court, thomas st, castleblayney",2 common court,thomas st,castleblayney
410508,898380,2019-11-15,"BEECHMOUNT, RAFEENAN, BALLINODE",unavailable,Monaghan,"212,500.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"beechmount, rafeenan, ballinode",beechmount,rafeenan,ballinode
410509,898393,2019-11-15,"CORRACLOUGHAN, CASTLEBLAYNEY, MONAGHAN",unavailable,Monaghan,"215,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"corracloughan, castleblayney, monaghan",corracloughan,castleblayney,monaghan
410510,898521,2019-11-18,"39 CABRA, THREEMILEHOUSE, MONAGHAN",unavailable,Monaghan,"125,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"39 cabra, threemilehouse, monaghan",39 cabra,threemilehouse,monaghan
410511,898458,2019-11-18,"12 OAK RIDGE, MONAGHAN, MONAGHAN",unavailable,Monaghan,"195,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"12 oak ridge, monaghan, monaghan",12 oak ridge,monaghan,monaghan
410512,898520,2019-11-18,"38 MONTFORT, MONAGHAN, MONAGHAN",unavailable,Monaghan,"240,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"38 montfort, monaghan, monaghan",38 montfort,monaghan,monaghan
410513,898727,2019-11-19,"76 O'NEILL PARK, CLONES, COUNTY MONAGHAN",unavailable,Monaghan,"56,500.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"76 o'neill park, clones, county monaghan",76 o'neill park,clones,county monaghan
410514,898658,2019-11-19,"188 BEECHGROVE LAWNS, DRUMBEAR, MONAGHAN TOWN",unavailable,Monaghan,"136,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"188 beechgrove lawns, drumbear, monaghan town",188 beechgrove lawns,drumbear,monaghan town
410515,898834,2019-11-20,"15 LATLORCAN GLEN, MONAGHAN, MONAGHAN",unavailable,Monaghan,"180,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"15 latlorcan glen, monaghan, monaghan",15 latlorcan glen,monaghan,monaghan
410516,899215,2019-11-21,"ARDKIRK, EMYVALE, MONAGHAN",unavailable,Monaghan,"155,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"ardkirk, emyvale, monaghan",ardkirk,emyvale,monaghan
410517,899158,2019-11-21,"53 ARDROSS AVE, CARRICKMACROSS, MONAGHAN",unavailable,Monaghan,"271,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"53 ardross ave, carrickmacross, monaghan",53 ardross ave,carrickmacross,monaghan
410518,899475,2019-11-22,"88 O'NEILL PARK, CLONES, CO MONAGHAN",unavailable,Monaghan,"35,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"88 o'neill park, clones, co monaghan",88 o'neill park,clones,co monaghan
410519,899831,2019-11-26,"26 MULLACH GLAS CRESCENT, MONAGHAN, CO. MONAGH...",unavailable,Monaghan,"145,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"26 mullach glas crescent, monaghan, co. monagh...",26 mullach glas crescent,monaghan,co. monaghan
410520,900375,2019-11-28,"6 MAPLE GROVE, SMITHBOROUGH, MONAGHAN",unavailable,Monaghan,"123,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"6 maple grove, smithborough, monaghan",6 maple grove,smithborough,monaghan
410521,900345,2019-11-28,"4 BRAMLEY GROVE, CASTLEBLANEY, MONAGHAN",unavailable,Monaghan,"143,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"4 bramley grove, castleblaney, monaghan",4 bramley grove,castleblaney,monaghan
410522,900559,2019-11-29,"14 ALDERWOOD, CLOUGHVALLEY, CARRICKMACROSS",unavailable,Monaghan,"195,000.00",No,No,Second-Hand Dwelling house /Apartment,unavailable,Leinster,2019-11-30,"14 alderwood, cloughvalley, carrickmacross",14 alderwood,cloughvalley,carrickmacross

In [21]:
# df_o = df_o['Address_lower'].str.split(',')

In [22]:
# df_o.head()

In [23]:
# time_mask = (df_o['Month_end_day'] > '2014-01-31') & (df_o['Month_end_day'] <= '2019-12-31')
# new_house_mask= (df_o['Description of Property'].str.contains("Second-Hand") )


# df_time = df_o.loc[mask]

In [33]:
df_o['Province'].unique()

array(['Leinster'], dtype=object)